# Generated by Django 2.0.6 on 2018-06-26 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('dno', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=32)),
                ('dposition', models.CharField(max_length=32)),
                ('dstate', models.CharField(default='normal', max_length=10)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='OccupySeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ustate', models.CharField(max_length=10)),
                ('reasonforleave', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'occupyseat',
            },
        ),
        migrations.CreateModel(
            name='PwdAndPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(max_length=32)),
                ('permission', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pwdandpermission',
            },
        ),
        migrations.CreateModel(
            name='ReservationDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
            ],
            options={
                'db_table': 'reservationrevice',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('sno', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sposition', models.CharField(max_length=32)),
                ('sstate', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uno', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=32)),
                ('upic', models.CharField(default='/static/data/huaji.png', max_length=64)),
                ('sex', models.CharField(max_length=3)),
                ('idnum', models.CharField(max_length=18)),
                ('duty', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=10)),
                ('companymail', models.EmailField(max_length=254)),
                ('personalmail', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField()),
                ('housephone', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='reservationdevice',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='pwdandpermission',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='occupyseat',
            name='s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seat'),
        ),
        migrations.AddField(
            model_name='occupyseat',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
