# Generated by Django 2.0.6 on 2018-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_device_dtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupyseat',
            name='reasonforleave',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
