# Generated by Django 2.0.6 on 2018-07-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180629_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip',
        ),
        migrations.AddField(
            model_name='seat',
            name='ip',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
    ]
