# Generated by Django 2.0.6 on 2018-07-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_seat_stype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ustate',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
