# Generated by Django 2.0.6 on 2018-07-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_ustate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdevice',
            name='d',
        ),
        migrations.RemoveField(
            model_name='reservationdevice',
            name='u',
        ),
        migrations.RemoveField(
            model_name='occupyseat',
            name='reasonforleave',
        ),
        migrations.RemoveField(
            model_name='occupyseat',
            name='ustate',
        ),
        migrations.AddField(
            model_name='occupyseat',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='occupyseat',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reasonforleave',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='ReservationDevice',
        ),
    ]
