# Generated by Django 2.0.6 on 2018-07-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180702_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOccupy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seat')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
            options={
                'db_table': 'currentoccupy',
            },
        ),
    ]
