# Generated by Django 2.0.6 on 2018-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_currentoccupy'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentoccupy',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
