# Generated by Django 2.0.7 on 2018-07-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_currentoccupy_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupyseat',
            name='reasonforleave',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
